### ISSUE TITLE
Feature request: copy version info from about dialog

### ISSUE THREAD

**Issue by assarbad** [CoatiSoftware/Sourcetrail#1012]
I'd find it extremely helpful to be able to press Ctrl+C (or some other shortcut that corresponds to "copy to clipboard" on a given system) when looking at the About dialog and if that action would copy as much relevant information into the clipboard as possible.

What's relevant should be defined as whatever you query from people like me reporting issues.

So as an example set:

* OS version, possibly also bitness and (user/system) language
* Sourcetrail version
* Installation path of Sourcetrail (to discern if it's running installed/portable)

As an alternative one could use edit fields for the information right below the logo. But something along the lines of Ctrl+C would be easier and could be incorporated into the issue templates here on GitHub.

![ctrl+c](https://user-images.githubusercontent.com/3238620/81821531-39de6100-9532-11ea-9854-12cfb24132e4.png)

Thanks for reading,

Oliver

**Comment by egraether** [comment]
Could also be solved by enabling text selection.

**Comment by mlangkabel** [comment]
Just to enable text selection would still not include info on portable/installed and the OS. But maybe we should add that info to the about window.

What about adding a "copy to clipboard" button? There are icons for that. And that would make it more easily recognizable for the user, in contrast to the "hidden" approach of allowing to press crtl-C in that dialog.
